[build]
target = "avr-none"

[target.'cfg(target_arch = "avr")']
rustflags = ["-C", "target-cpu=atmega328p"]
runner = "ravedude"

[target.avr-none]
rustflags = ["-C", "target-cpu=atmega328p"]

[target.x86_64-unknown-linux-gnu]
rustflags = []
